apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service.yaml
- deployment.yaml
- middleware-redirect-scheme.yaml
- route.yaml

namespace: argocd-app

commonLabels:
  app: argocd-app
  env: dev

namePrefix: argocd-app-

images:
- name: cams7/argocd-app
  newName: cams7/argocd-app
  newTag: 8c95216c708f293b30c1d446c3ea60207d5925c5
