apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service.yaml
- deployment.yaml
- middleware-redirect-scheme.yaml
- route.yaml

namespace: argocd-app

commonLabels:
  app: argocd-app
  env: dev

namePrefix: argocd-app-
images:
- name: public.nexus.cams7.ml/argocd-app
  newName: public.nexus.cams7.ml/argocd-app
  newTag: 6c502b21f2266fed7fd2a96d2170a91ce17a7274
