apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service.yaml
- deployment.yaml
- middleware-redirect-scheme.yaml
- route.yaml

namespace: argocd-app

commonLabels:
  app: argocd-app
  env: dev

namePrefix: argocd-app-

images:
- name: cams7/argocd-app
  newName: cams7/argocd-app
  newTag: 1d8f54848199e9361789257893428667544af350
