apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service.yaml
- deployment.yaml
- middleware-redirect-scheme.yaml
- route.yaml

namespace: argocd-app

commonLabels:
  app: argocd-app
  env: dev

namePrefix: argocd-app-