apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service.yaml
- deployment.yaml
- middleware-redirect-scheme.yaml
- route.yaml

namespace: argocd-app

commonLabels:
  app: argocd-app
  env: dev

namePrefix: argocd-app-
images:
- name: public.nexus.cams7.ml/argocd-app
  newName: public.nexus.cams7.ml/argocd-app
  newTag: 2407dc24c534e341d94744080b08fec98a25f815
