name: Build and push docker image

on:
  workflow_call:
    inputs:
      imageName:
        required: true
        type: string
      imageVersion:
        required: true
        type: string
      builtFile:
        required: true
        type: string
    secrets:
      username:
        required: true
      password:
        required: true

jobs:
  build-and-push-docker:
    name: Build and push
    runs-on: self-hosted
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - name: List files in the workspace
        shell: bash
        run: |
          pwd 
          ls -hal ${{ runner.workspace }}

      - name: List files in the temp
        shell: bash
        run: |
          pwd 
          ls -hal ${{ runner.temp }}

      - name: List files in the cache
        shell: bash
        run: |
          pwd 
          ls -hal ${{ runner.tool_cache }}
          
      - id: download-build-file
        name: Download built file
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.builtFile }} 
          
      - name: List files in the repository after download
        shell: bash
        run: |
          ls -hal ${{ github.workspace }}

      - id: set-up-qemu
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - id: set-up-docker-buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - id: login-to-nexus
        name: Login to Nexus
        uses: docker/login-action@v1
        with:
          registry: private.nexus.cams7.ml
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - run: echo Docker image version is ${{ inputs.imageVersion }}
      
      - id: build-and-push
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            private.nexus.cams7.ml/${{ inputs.imageName }}:${{ inputs.imageVersion }} 
            private.nexus.cams7.ml/${{ inputs.imageName }}:latest

      - id: remove-built-file
        name: Remove built file
        shell: bash
        run: rm ${{ inputs.builtFile }}