name: Build and push docker image

on:
  workflow_call:
    inputs:
      imageName:
        required: true
        type: string
      imageVersion:
        required: true
        type: string
      dockerContext:
        required: false
        type: string
        default: ${{ github.workspace }}
      appInfo:
        required: true
        type: string
    secrets:
      nexusUsername:
        required: true
      nexusPassword:
        required: true

jobs:
  build-and-push-docker:
    name: Build and push
    runs-on: self-hosted
    steps:
      - id: set-up-qemu
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - id: set-up-docker-buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - id: login-to-nexus
        name: Login to Nexus
        uses: docker/login-action@v1
        with:
          registry: private.nexus.cams7.ml
          username: ${{ secrets.nexusUsername }}
          password: ${{ secrets.nexusPassword }}
      
      - id: build-and-push
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.dockerContext }}
          push: true
          secrets: ${{ inputs.appInfo }}
          tags: |
            private.nexus.cams7.ml/${{ inputs.imageName }}:${{ inputs.imageVersion }} 
            private.nexus.cams7.ml/${{ inputs.imageName }}:latest