name: Continuous delivery

on:
  push:
    branches: [main]

jobs:
  build-go:
    name: Build Go
    runs-on: self-hosted   
    
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

#      - uses: sonarsource/sonarqube-scan-action@master
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

#      - uses: sonarsource/sonarqube-quality-gate-action@master
#        timeout-minutes: 2
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - id: setup-up-go
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - id: build-go
        name: Build Go
        run: CGO_ENABLED=0 go build -o server main.go

  buid-push-docker:
    name: Build and push Docker
    needs: build-go
    uses: cams7-tests/argocd-app/.github/workflows/build-push-docker.yaml@17e2c802f8fdc179823e6e0c197dd584a7c6f393
    with:
      imageName: argocd-app
      imageVersion: ${{ github.sha }}
    secrets:
      nexusUsername: ${{ secrets.NEXUS_USERNAME }}
      nexusPassword: ${{ secrets.NEXUS_TOKEN }}

  update-kustomize:
    name: Update Kustomize
    needs: buid-push-docker
    uses: cams7-tests/argocd-app/.github/workflows/update-image-kustomize.yaml@17e2c802f8fdc179823e6e0c197dd584a7c6f393
    with:
      imageName: argocd-app
      imageVersion: ${{ github.sha }}
      kustomizePath: k8s