name: CD
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build image and push to docker hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: cams7
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cams7/argocd-app
          tags: ${{ github.sha }}, latest
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: v3.6.1

      - name: update k8s
        run: |
          cd k8s
          kustomize edit set image cams7/argocd-app=cams7/argocd-app:${{ github.sha }}

      - name: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy Action"
          git commit -am "Change image tag"

      - name : push
        uses: ad-m/github-push-action@master

        
      


