name: CD
on:
  push:
    branches: [main]
jobs:
  buildApp:
    name: Build App
    runs-on: self-hosted
    steps:
      - name: Checkout App
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build Go App
        run: CGO_ENABLED=0 go build -o server main.go

#      - name: Test App
#        run: go test -v ./...

  createDockerImage:
    name: Create Docker image
    runs-on: self-hosted
    needs: buildApp
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Nexus
        uses: docker/login-action@v1
        with:
          registry: private.nexus.cams7.ml
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_TOKEN }}

      - name: Show files in current diretory
        run: |
          pwd
          ls -hal
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            private.nexus.cams7.ml/argocd-app:${{ github.sha }} 
            private.nexus.cams7.ml/argocd-app:latest

      - name: Remove Go generated binary file
        run: rm server

  updateK8s:
    name: Update K8s
    runs-on: self-hosted
    needs: createDockerImage
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: v3.6.1

      - name: Update k8s
        run: |
          cd k8s
          kustomize edit set image public.nexus.cams7.ml/argocd-app=public.nexus.cams7.ml/argocd-app:${{ github.sha }}

      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy Action"
          git commit -am "Change image tag"

      - name : Push
        uses: ad-m/github-push-action@master

        
      


