name: Continuous delivery

on:
  push:
    branches: [main]

env:
  APP_VERSION: ${{ github.sha }}

jobs:
  build-go:
    name: Build Go aplication
    runs-on: self-hosted   
    
    steps:
      - run: echo "Docker image version is ${{ env.APP_VERSION }}"

#      - env:
#          APP_VERSION: ${{ github.sha }}
#        run: echo "Docker image version is ${{ echo APP_VERSION }}"

      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

#      - uses: sonarsource/sonarqube-scan-action@master
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

#      - uses: sonarsource/sonarqube-quality-gate-action@master
#        timeout-minutes: 2
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - id: setup-up-go
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - id: build-go
        name: Build Go
        run: CGO_ENABLED=0 go build -o server main.go

#      - name: Test
#        run: go test -v ./...

      - name: List files in the workspace
        shell: bash
        run: |
          echo ${{ runner.workspace }} 
          ls -hal ${{ runner.workspace }}/argocd-app

      - name: List files in the temp
        shell: bash
        run: |
          echo ${{ runner.temp }} 
          ls -hal ${{ runner.temp }}/_github_workflow
          ls -hal ${{ runner.temp }}/_runner_file_commands

      - name: List files in the cache
        shell: bash
        run: |
          echo  ${{ runner.tool_cache }} 
          ls -hal ${{ runner.tool_cache }}
          
      - name: Upload built file
        uses: actions/upload-artifact@v2
        with:
          name: server
          path: server   

  buid-push-docker:
    name: Build and push Docker image
    needs: build-go
    uses: cams7-tests/argocd-app/.github/workflows/build-push-docker.yaml@b2a7fddbdbcabbed0e1ea09222b9ea36c7d8e77e
    with:
      imageName: argocd-app
      imageVersion: ${{ env.APP_VERSION }}
      builtFile: server
    secrets:
      username: ${{ secrets.NEXUS_USERNAME }}
      password: ${{ secrets.NEXUS_TOKEN }}

  deploy:
    name: Deploy
    runs-on: self-hosted
    needs: buid-push-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: v3.6.1

      - run: echo Docker image version is ${{ env.APP_VERSION }}

      - name: Update k8s
        run: |
          cd k8s
          kustomize edit set image public.nexus.cams7.ml/argocd-app=public.nexus.cams7.ml/argocd-app:${{ env.APP_VERSION }}

      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy Action"
          git commit -am "Change image tag"

      - name : Push
        uses: ad-m/github-push-action@master

        
      


