name: Update Docker image on Kustomize file

on:
  workflow_call:
    inputs:
      imageName:
        required: true
        type: string
      imageVersion:
        required: true
        type: string
      kustomizePath:
        required: true
        type: string  
      gitEmail:
        required: false
        type: string  
        default: "action@github.com"
      gitUsername:
        required: false
        type: string
        default: "Deploy Action"
      gitCommitMessage:
        required: false
        type: string  
        default: "Change image tag"
    secrets:
      nexusUsername:
        required: true
      nexusPassword:
        required: true

jobs:
  update-kustomize:
    name: Update Docker image on Kustomize
    runs-on: self-hosted
    needs: buid-push-docker
    steps:
      - run: |
          echo imageName is ${{ inputs.imageName }}
          echo imageVersion is ${{ inputs.imageVersion }}
          echo kustomizePath is ${{ inputs.kustomizePath }}
          echo gitEmail is ${{ inputs.gitEmail }}
          echo gitUsername is ${{ inputs.gitUsername }}
          echo gitCommitMessage is ${{ inputs.gitCommitMessage }}

      - id: kustomize
        name: Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: v3.6.1

      - id: update-kustomize-file
        name: Update Kustomize file
        run: |
          cd ${{ inputs.kustomizePath }}
          kustomize edit set image public.nexus.cams7.ml/${{ inputs.imageName }}=public.nexus.cams7.ml/${{ inputs.imageName }}:${{ inputs.imageVersion }}

      - id: commit
        name: Commit
        run: |
          git config --local user.email "${{ inputs.gitEmail }}"
          git config --local user.name "${{ inputs.gitUsername }}"
          git commit -am "Change image ${{ inputs.gitCommitMessage }}"

      - id: push
        name : Push
        uses: ad-m/github-push-action@master